// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGvYQEwD1TuJ7fIMUhLFCQtcetWsnLeG4',
    appId: '1:641961655445:web:1d41fcec1a35ea7328af9c',
    messagingSenderId: '641961655445',
    projectId: 'instagram-clone-7266c',
    authDomain: 'instagram-clone-7266c.firebaseapp.com',
    storageBucket: 'instagram-clone-7266c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvgucPYtQH_6K2auVhWon0fgbhCL4FJZ4',
    appId: '1:641961655445:android:75fb95fd7c6847ae28af9c',
    messagingSenderId: '641961655445',
    projectId: 'instagram-clone-7266c',
    storageBucket: 'instagram-clone-7266c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACsZH6Qs88fgE6jTSd1AEx9gDJoTu8DS8',
    appId: '1:641961655445:ios:b025b8196a58925c28af9c',
    messagingSenderId: '641961655445',
    projectId: 'instagram-clone-7266c',
    storageBucket: 'instagram-clone-7266c.appspot.com',
    iosClientId: '641961655445-5hg6qqap4g30ne3rnmbf0du2etu1ti9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACsZH6Qs88fgE6jTSd1AEx9gDJoTu8DS8',
    appId: '1:641961655445:ios:8d8f6faff2ca00c928af9c',
    messagingSenderId: '641961655445',
    projectId: 'instagram-clone-7266c',
    storageBucket: 'instagram-clone-7266c.appspot.com',
    iosClientId: '641961655445-psp7cr19krcq9h3cs1ftuh07bql9m8o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstagramClone.RunnerTests',
  );
}
